### ISSUE TITLE
Unable to create MosesTokenizer object in Python 2.7

### ISSUE THREAD

**Issue by sidhiadkoli** [alvations/sacremoses#2]
I am unable to create MosesTokenizer or MosesDetokenizer objects in Python 2.7.

```python
>>> from sacremoses import MosesTokenizer        
>>> mt = MosesTokenizer()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sidhi/.local/lib/python2.7/site-packages/sacremoses/tokenize.py", line 209, in __init__
    super(MosesTokenizer, self).__init__()
TypeError: super() argument 1 must be type, not classobj
```

Is this module supported for Python 2.7?

**Comment by alvations** [comment]
I tried my best not to support Python2.7 but I gave in on https://github.com/alvations/sacremoses/issues/4 


Do an upgrade:

```
pip install -U sacremoses
```

And the super error should go away =)

```python
$ python
Python 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 12:01:12) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from sacremoses import MosesTokenizer, MosesDetokenizer
>>> mt = MosesTokenizer()
>>> text = u'This, is a sentence with weird\xbb symbols\u2026 appearing everywhere\xbf'
>>> expected_tokenized = u'This , is a sentence with weird \xbb symbols \u2026 appearing everywhere \xbf'
>>> tokenized_text = mt.tokenize(text, return_str=True)
>>> tokenized_text == expected_tokenized
True
>>> exit()
```
