### ISSUE TITLE
normalize broken

### ISSUE THREAD

**Issue by mjpost** [alvations/sacremoses#89]
Running 0.38 installed via pip:

```bash
$ echo "This is a test" | sacremoses normalize
Traceback (most recent call last):
  File "/usr/local/bin/sacremoses", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/sacremoses/cli.py", line 297, in normalize_file
    pre_replace_unicode_punct=replace_unicode_punct,
NameError: name 'replace_unicode_punct' is not defined
```

Tested in two environments (Mac and Linux).

**Comment by diegacu** [comment]
I have the same issue, tested in a Linux environment.

**Comment by alvations** [comment]
Sorry for the typo. Fixed this in the last commit.  Please update your `sacremoses` version

```
$ sacremoses --version
sacremoses, version 0.0.39

$ echo "This is a test" | sacremoses normalize
100%|█████████████| 1/1 [00:00<00:00, 423.37it/s]
This is a test
```

Please install the latest version. Sorry for the inconvenience caused. 
I was away for a while for other commitments.
